version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend:local
    