apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      containers:
      - name: backend-feed 
        image: huybt2/udagram-api-feed:v9
        ports:
          - containerPort: 8080
        env:
            - name: POSTGRES_USERNAME
              valueFrom:
                secretKeyRef:
                  name: udagramdb-secret
                  key: POSTGRES_USERNAME
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: udagramdb-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key: POSTGRES_HOST
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key: POSTGRES_DB
            - name: JWT_SECRET
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key: JWT_SECRET
            - name:   AWS_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key:   AWS_BUCKET
            - name: AWS_REGION
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key: AWS_REGION
            - name: AWS_PROFILE
              valueFrom:
                configMapKeyRef:
                  name: udagram-env
                  key: AWS_PROFILE
        volumeMounts:
          - name: aws-secret
            mountPath: "/root/.aws"
            readOnly: true
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"
      volumes:
        - name: aws-secret
          secret:
            secretName: aws-secret
            items:
              - key: credentials
                path: credentials