apiVersion: apps/v1
kind: Deployment
metadata:
  name: fontdend
  labels:
    app: fontdend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fontdend
  template:
    metadata:
      labels:
        app: fontdend
    spec:
      containers:
      - name: fontdend 
        image: huybt2/udagram-frontend:v2
        ports:
          - containerPort: 80
        resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"  
        
